# -*- coding: utf-8 -*-
"""Additional LevelStories emitters — called from build_level_story_bundles.main."""
from __future__ import annotations


def emit_remaining_story_bundles(emit) -> None:
    """ja, ko, zh, ar, hi, ur — gameplay-faithful compact banners (TMP rich text)."""
    # Japanese
    emit("ja", {
        0: "<color=#c4b5fd><b>導関数</b></color>＝接線の傾き。<b>f(x)</b>がどれだけ速く上下するか。\n\n金色が道、水色がf'(x)で<i>床が続く場所</i>を形作る。|f'|が十分大きいと足場が支え、小さいと虚空が開く。\n\n<size=88%><color=#94a3b8><b>第一原理の思考:</b>比喩を剥がして事実まで下り、再構築する。<b>f</b>は成果の物語、<b>f'</b>は入力の感度。</color></size>",
        1: "旅人は坂が優しい所を歩く。導関数が負に転じると地面が途切れ、隙間が現れる。",
        2: "曲線は息のように上下する。導関数は着地地点を示す：正なら踏みしめ、負なら跳ぶ。",
        3: "余弦は導関数の符号に意味を隠す。ポップが危険の合図。",
        4: "絶対値は曲線を折り畳み一本道にする。頂点で導関数が反転し、床もひっくり返る。",
        5: "<color=#86efac>テイラー多項式</color>は滑らかな関数に近づく。<b>マクローリン</b>は<b>0</b>中心のテイラー。\n\n道は<b>e^u</b>の部分和——指数級数へ積み上がる多項式。",
        6: "<color=#7dd3fc>uの奇数乗</color>が符号を交互に変える——<b>sin(u)</b>のマクローリンDNA。\n\n打ち切られたテイラーの塔が正弦波へ伸びる。",
        7: "<color=#f5d0fe>等比級数</color>が<b>u</b>のべきを積む。収束半径の内側では尾が細り部分和が落ち着く。\n\n有限和の導関数が地形を変える。",
        8: "<b>z = x² − y₀²</b>（<b>y₀</b>固定）は鞍面の<color=#38bdf8>切断</color>。\n\nxの微分がマルチ変数の景観を1次元走行で読む。",
        9: "今度は<b>z = x² + y₀²</b>——<color=#fde047>楕円放物面</color>。<b>y₀</b>固定は皿状の断面。\n\n勾配は上り方向、走りでどれだけ急か見える。",
        10: "非負レートの<color=#fde047>定積分</color>は<b>積み上げ量</b>——すなわち曲線下の面積。\n\n青い柱は<b>リーマン和</b>：Δxで切り、f(x*)·Δxを足す→∫fへ。\n\n<size=92%><color=#a8b2d1>足場は滑らかなグラフを辿り、塗りは積分の近似。</color></size>",
        11: "<b>左リーマン:</b> 高さ<b>f(xᵢ)</b>——<color=#f87171>左端</color>。fが増関数なら和は面積<b>過小</b>。\n\n<size=92%><color=#a8b2d1>低い段の階段が放物線の下で保守的に伸びる。</color></size>",
        12: "<b>右リーマン:</b> <b>f(xᵢ₊₁)</b>——<color=#38bdf8>右端</color>。増関数なら<b>過大</b>——左の鏡。\n\n<size=92%><color=#a8b2d1>段は右端で跳ねる。左ステージと比較してみて。</color></size>",
        13: "<b>中点則:</b> 区間の<color=#86efac>中点</color>で高さ。対称な帯で滑らか曲線によく合う。\n\n<size=92%><color=#a8b2d1>段は各スライスの真ん中に乗る。</color></size>",
        14: "<b>減衰振動</b>はバネ・回路・構造に登場。包絡線が<color=#38bdf9>縮み</color>指数×正弦。\n\n<size=92%><color=#a8b2d1>グラフは坂道、導関数が峰の近くの安全柱を決める。</color></size>",
        15: "吊り鎖は<b>懸垂線</b>——多くは<color=#fde047>cosh</color>で模型化。投げ物の放物線とは別：自重下の張力バランス。\n\n<size=92%><color=#a8b2d1>アーチやケーブルの感覚。</color></size>",
        16: "<b>|sin(x)|</b>は全波整流された正弦——<color=#f0abfc>下側を折り上げ</color>。零点で角、導関数は跳ぶ。\n\n<size=92%><color=#a8b2d1>純粋三角から電源波形の橋。</color></size>",
        17: "<b>BC: 逆三角</b>。<color=#38bdf8>arctan</color>は1/(1+x²)で傾きが有界。水平漸近線が±∞の視覚。\n\n<size=92%><color=#a8b2d1>積分と幾何の定番。</color></size>",
        18: "<b>ロジスティック:</b> dP/dt = kP(1−P/L)。初期はほぼ指数、<color=#86efac>飽和</color>へ曲がる容量<b>L</b>。\n\n<size=92%><color=#a8b2d1>変曲点で成長率最大。</color></size>",
        19: "<b>極座標</b><color=#fde047>(r,θ)</color>。<b>心臓線</b> r ~ 1+cos θ。\n\n<size=92%><color=#a8b2d1>極面積 ½∫r² dθ。</color></size>",
        20: "<b>極バラ</b> r ~ cos(nθ)。対称が花弁数を決める。\n\n<size=92%><color=#a8b2d1>導関数のポップがrの急変——花弁の縁の壁。</color></size>",
        21: "<b>sinh/cosh</b>、恒等式 cosh²−sinh²=1。ODEやケーブルで三角形に似た仲間。\n\n<size=92%><color=#a8b2d1>sinhは0から立つ奇関数パートナー。</color></size>",
        22: "<b>物理C:</b> Q = Q₀ e^{−t/τ}。RC/RLの時定数。\n\n<size=92%><color=#a8b2d1>グラフは沈み、導関数はまだゼロへ漏れる符号。</color></size>",
        23: "<b>回転</b><color=#7dd3fc>L = Iω</color>、トルクτ = dL/dt。\n\n<size=92%><color=#a8b2d1>小振幅はSHMと同系、エネルギーの行き来。</color></size>",
        24: "<b>投擲高さ y(t)</b>——下向き<color=#fde047>放物線</color>。v=0が頂点。\n\n<size=92%><color=#a8b2d1>y,v,aの三歩。</color></size>",
        25: "<b>cos のマクローリン</b>は偶数乗が符号交互。\n\n<size=92%><color=#a8b2d1>項を足すほど0近傍が改善。</color></size>",
        26: "<b>ln x</b>と∫dx/x。定義域は正側にシフト。\n\n<size=92%><color=#a8b2d1>正の傾きは遠ざかるほど小さく。</color></size>",
        27: "<b>√x</b>は0⁺で傾きが爆発（BCの古典）。\n\n<size=92%><color=#a8b2d1>ゲームは滑らかに見せるが解析は境界に注意。</color></size>",
        28: "<b>tan x</b>は漸近線の間の1枝。sec²x。\n\n<size=92%><color=#a8b2d1>パラメトリック/極で骨格となる。</color></size>",
        29: "<b>y′=ky → Ce^{kx}</b>。分離、場、半減期の周辺。\n\n<size=92%><color=#a8b2d1>量に比例する変化率。</color></size>",
        30: "<b>位相とSHM</b> sin(ωt+ϕ)。\n\n<size=92%><color=#a8b2d1>導関数は（定数倍まで）cos——誰が先行か。</color></size>",
        31: "<b>三次</b>：臨界点、<color=#fca5a5>変曲点</color>で曲率が反転。\n\n<size=92%><color=#a8b2d1>山と谷の間の典型パターン。</color></size>",
        32: "<b>b^x</b>の微分は(ln b)b^x。\n\n<size=92%><color=#a8b2d1>底をeへつなぐ定数。</color></size>",
        33: "<b>円</b>(x−h)²+(y−k)²=R²。ここは上側半円y=k+√(⋯)。\n\n<size=92%><color=#a8b2d1>陰関数微分と媒介表示はAPの定番。</color></size>",
        34: "<b>揚力C_L(α)</b>がだいたい線形、<b>失速</b>で崩れる。\n\n<size=92%><color=#a8b2d1>教育用シルエット（実機はもっと複雑）。</color></size>",
        35: "<b>抗力極曲線</b><color=#c4b5fd>C_D = C_{D0} + K C_L²</color>。\n\n<size=92%><color=#a8b2d1>最適C_L周りの滑走比の感覚。</color></size>",
        36: "<b>等温大気カートゥーン</b>：ρ ~ <color=#86efac>e^{−h/H}</color>。\n\n<size=92%><color=#a8b2d1>動圧などρ(h)に乗る物すべて。</color></size>",
        37: "<b>フーゴイド/短周期</b>を減衰振動で漫画化。\n\n<size=92%><color=#a8b2d1>実機の制御はもっと豊か。</color></size>",
        38: "<b>ニュートン的</b>風上圧力～<color=#fca5a5>sin²α</color>の教養モデル。\n\n<size=92%><color=#a8b2d1>CFDの代替ではない。</color></size>",
        39: "<b>ストルーハル</b>：f ≈ St·U/D、渦放出のトーン。\n\n<size=92%><color=#a8b2d1>振動と騒音の指針。</color></size>",
        40: "<b>再突入</b>の熱脅威カーブを質的に緩めるイメージ。\n\n<size=92%><color=#a8b2d1>定量メモではない。</color></size>",
        41: "<b>ドットコムバブル</b> — 模式化インデックス（実S&amp;Pではない）。\n\n<size=92%><color=#a8b2d1>上昇・エアポケット・緩い回復の教学シルエット。</color></size>",
        42: "<b>2008年危機</b> — 住宅・信用ストレスの雰囲気、定性曲線のみ。\n\n<size=92%><color=#a8b2d1>実データの再現ではない。</color></size>",
        43: "<b>マンデルブロ集合</b>：c平面の滑らか脱出時間、<color=#86efac>Re(c)</color>固定の切断。\n\n<size=92%><color=#a8b2d1>ジュリアの境界；深いズームは別エンジン。|Im(c)|切断。</color></size>",
    })

    # Korean (compact)
    emit("ko", {
        0: "<color=#c4b5fd><b>도함수</b></color>=접선의 기울기.<b>f(x)</b>가 얼마나 빨리 오르내리는가.\n\n금빛은 길, 얼음빛 f'(x)는 <i>바닥이 버티는 곳</i>을 만든다. |f'|이 충분하면 발판이 이어지고, 아니면 공허가 열린다.\n\n<size=88%><color=#94a3b8><b>퍼스트 프린시플:</b> 비유를 깎아 사실로 내려가 다시 조립한다. <b>f</b>는 결과 모델, <b>f'</b>는 입력 민감도.</color></size>",
        1: "여행자는 완만한 기울기를 걷는다. 도함수가 음이 되면 땅이 갈라진다.",
        2: "곡선은 숨처럼 오르내린다. 도함수가 어디에 발을 딛을지 알려 준다.",
        3: "코사인은 도함수 부호 속에 의미를 숨긴다. 팝이 위험을 알린다.",
        4: "절댓값은 곡선을 한 길로 접는다. 꼭짓점에서 도함수가 뒤집히고 바닥도 바뀐다.",
        5: "<color=#86efac>테일러 다항식</color>이 매끈한 함수를 닮는다.<b>매클로린</b>은 <b>0</b>에서의 테일러.\n\n여기서는 <b>e^u</b>의 부분합 길.",
        6: "<color=#7dd3fc>홀수 거듭제곱</color>이 부호를 번갈아 — <b>sin(u)</b>의 매클로린 DNA.\n\n자른 타워가 사인파로 올라간다.",
        7: "<color=#f5d0fe>등비급수</color>가 <b>u</b>의 거듭제곱을 쌓는다. 반경 안에서 꼬리가 줄어든다.\n\n유한합의 도함수가 지형을 바꾼다.",
        8: "<b>z = x² − y₀²</b> — 안장면의 <color=#38bdf8>단면</color>.\n\nx 도함수가 다변수 풍경을 1차원 달리기로 읽는다.",
        9: "이제 <b>z = x² + y₀²</b> — <color=#fde047>타원 포물면</color>. y₀ 고정은 접시 단면.\n\n경사는 위쪽, 달리며 경사가 얼마나 급한지 보인다.",
        10: "<color=#fde047>정적분</color>은 누적량—곡선 아래 넓이.\n\n파란 기둥은 <b>리만합</b> f(x*)·Δx → ∫f.\n\n<size=92%><color=#a8b2d1>발은 매끈한 그래프를, 음영은 적분을 근사.</color></size>",
        11: "<b>왼쪽 리만:</b> <b>f(xᵢ)</b> — <color=#f87171>왼쪽 끝</color>. 증가 함수면 <b>과소</b> 추정.\n\n<size=92%><color=#a8b2d1>낮은 계단이 포물선 아래 보수적으로.</color></size>",
        12: "<b>오른쪽 리만:</b> <b>f(xᵢ₊₁)</b> — <color=#38bdf8>오른쪽</color>. 증가면 <b>과대</b>.\n\n<size=92%><color=#a8b2d1>왼쪽 무대와 거울.</color></size>",
        13: "<b>중점:</b> <color=#86efac>가운데</color> 샘플. 대칭 띠가 곡선에 잘 맞는다.\n\n<size=92%><color=#a8b2d1>각 조각 한가운데 계단.</color></size>",
        14: "<b>감쇠 진동</b> — 스프링·회로. 포락선이 <color=#38bdf9>줄며</color> 지수×사인.\n\n<size=92%><color=#a8b2d1>도함수가 봉우리 근처 안전 기둥을 고른다.</color></size>",
        15: "매달린 사슬은 <b>현수선</b>, 종종 <color=#fde047>cosh</color>. 포물선 포병과는 다르다.\n\n<size=92%><color=#a8b2d1>아치·케이블의 감각.</color></size>",
        16: "<b>|sin(x)|</b> — <color=#f0abfc>전파 정류</color> 파형. 영점에서 꼭짓점.\n\n<size=92%><color=#a8b2d1>삼각에서 전원 파형으로.</color></size>",
        17: "<b>BC 역삼각.</b> <color=#38bdf8>arctan</color>, 1/(1+x²). 수평 점근선.\n\n<size=92%><color=#a8b2d1>적분·기하 단골.</color></size>",
        18: "<b>로지스틱:</b> dP/dt = kP(1−P/L). 초반 거의 지수, <color=#86efac>포화</color>로 휨.\n\n<size=92%><color=#a8b2d1>변곡점에서 성장 최대.</color></size>",
        19: "<b>극좌표</b> <color=#fde047>(r,θ)</color>. <b>심장형</b> r ~ 1+cos θ.\n\n<size=92%><color=#a8b2d1>극면적 ½∫r² dθ.</color></size>",
        20: "<b>장미곡선</b> r ~ cos(nθ).\n\n<size=92%><color=#a8b2d1>도함수 팝이 r 급변—꽃잎 가장자리.</color></size>",
        21: "<b>sinh/cosh</b>, 쌍곡 항등식. ODE·케이블.\n\n<size=92%><color=#a8b2d1>sinh는 0에서 시작하는 홀드 파트너.</color></size>",
        22: "<b>물리C:</b> Q = Q₀ e^{−t/τ}. RC/RL 시정수.\n\n<size=92%><color=#a8b2d1>그래프는 가라앉고 도함수는 여전히 누설 부호.</color></size>",
        23: "<b>회전</b> <color=#7dd3fc>L = Iω</color>, τ = dL/dt.\n\n<size=92%><color=#a8b2d1>소각진동 SHM과 같은 계열.</color></size>",
        24: "<b>포물선 높이 y(t)</b> — 시간의 <color=#fde047>포물선</color>. v=0이 꼭짓점.\n\n<size=92%><color=#a8b2d1>y,v,a 연쇄.</color></size>",
        25: "<b>cos 매클로린</b> 짝수 거듭제곱.\n\n<size=92%><color=#a8b2d1>항을 더할수록 0 근처가 좋아진다.</color></size>",
        26: "<b>ln x</b>와 ∫dx/x.\n\n<size=92%><color=#a8b2d1>양의 기울기는 멀수록 작아진다.</color></size>",
        27: "<b>√x</b> 0⁺에서 기울기 폭발.\n\n<size=92%><color=#a8b2d1>게임은 매끈하지만 해석은 경계 주의.</color></size>",
        28: "<b>tan x</b> 점근선 사이 한 가지. sec²x.\n\n<size=92%><color=#a8b2d1>BC 삼각의 뼈대.</color></size>",
        29: "<b>y′=ky → Ce^{kx}</b>.\n\n<size=92%><color=#a8b2d1>량에 비례하는 변화율.</color></size>",
        30: "<b>위상·SHM</b>.\n\n<size=92%><color=#a8b2d1>도함수는 cos(상수차).</color></size>",
        31: "<b>삼차</b> — 극값, <color=#fca5a5>변곡점</color>.\n\n<size=92%><color=#a8b2d1>언덕·골짜기 패턴.</color></size>",
        32: "<b>b^x</b> 도함수 (ln b)b^x.\n\n<size=92%><color=#a8b2d1>밑 e로 가는 다리.</color></size>",
        33: "<b>원</b> — 상반원 y=k+√(⋯).\n\n<size=92%><color=#a8b2d1>은함수·매개 AP 단골.</color></size>",
        34: "<b>양력 C_L(α)</b> 선형+\n<b>실속(스톨)</b>.\n\n<size=92%><color=#a8b2d1>교육용 실루엣.</color></size>",
        35: "<b>항력 극곡선</b> C_D = C_{D0} + K C_L².\n\n<size=92%><color=#a8b2d1>최적 C_L·활공비 감각.</color></size>",
        36: "<b>등온 대기</b> ρ ~ e^{−h/H}.\n\n<size=92%><color=#a8b2d1>동압 등 ρ(h) 추종.</color></size>",
        37: "<b>퓨고이드/단주기</b> 감쇠 만화.\n\n<size=92%><color=#a8b2d1>실제 제어는 더 복잡.</color></size>",
        38: "<b>뉴턴 sin²α</b> 교양 모델.\n\n<size=92%><color=#a8b2d1>CFD 아님.</color></size>",
        39: "<b>스트루할</b> vortex 톤.\n\n<size=92%><color=#a8b2d1>f ≈ St·U/D.</color></size>",
        40: "<b>재진입</b> 열 위협 완화 질서.\n\n<size=92%><color=#a8b2d1>정량 메모 아님.</color></size>",
        41: "<b>닷컴 버블</b> — 스타일화 지수 경로(실제 S&amp;P 데이터 아님).\n\n<size=92%><color=#a8b2d1>급등·급락·회복 — 교육용 형태.</color></size>",
        42: "<b>2008 위기</b> — 주택·크레딧 스트레스 분위기, 질적 곡선.\n\n<size=92%><color=#a8b2d1>실제 시계열 복제 아님.</color></size>",
        43: "<b>만델브로</b> c평면, 탈출시간, Re 고정 절편.\n\n<size=92%><color=#a8b2d1>줄리아 경계; 딥 줌은 다른 엔진.</color></size>",
    })

    # Simplified Chinese
    emit("zh", {
        0: "<color=#c4b5fd><b>导数</b></color>=切线斜率：<b>f(x)</b>变化多快。\n\n金光为路径，冰蓝f'(x)决定<i>地面承载</i>何处。|f'|够大才有平台，否则裂开虚空。\n\n<size=88%><color=#94a3b8><b>第一性原理：</b>剥离类比直到事实，再向上推理。<b>f</b>是结果故事，<b>f'</b>是输入敏感度。</color></size>",
        1: "旅人在缓坡行走。导数为负，地面变薄成缝。",
        2: "曲线像呼吸升降。导数告诉你落点：正可踏，负需跳。",
        3: "余弦把意义藏在导数符号里。“弹出”预告危险。",
        4: "绝对值把曲线折成一路。在拐点导数翻转，地面也翻转。",
        5: "<color=#86efac>泰勒多项式</color>贴近光滑函数。<b>麦克劳林</b>是中心在<b>0</b>的泰勒。\n\n此处是<b>e^u</b>的部分和之路。",
        6: "<color=#7dd3fc>u的奇次幂</color>交替符号—<b>sin(u)</b>的麦克劳林基因。\n\n截断塔攀向正弦波。",
        7: "<color=#f5d0fe>等比级数</color>堆叠<b>u</b>的幂。半径内尾项收缩。\n\n有限和的导数重塑地形。",
        8: "<b>z = x² − y₀²</b> — 鞍面的<color=#38bdf8>切片</color>。\n\n对x的导数用一维跑酷读多元图景。",
        9: "现在<b>z = x² + y₀²</b> — <color=#fde047>椭圆抛物面</color>。固定y₀得像碗。\n\n梯度指向上坡，切片显示爬升多陡。",
        10: "<color=#fde047>定积分</color>累加速率得<b>总量</b>—曲线下面积。\n\n蓝柱是<b>黎曼和</b> Δx、f(x*)·Δx 逼近∫f。\n\n<size=92%><color=#a8b2d1>路径沿光滑曲线，阴影近似积分。</color></size>",
        11: "<b>左黎曼：</b><b>f(xᵢ)</b> — <color=#f87171>左端</color>。f递增则和<b>低估</b>面积。\n\n<size=92%><color=#a8b2d1>抛物线下的保守台阶。</color></size>",
        12: "<b>右黎曼：</b><b>f(xᵢ₊₁)</b> — <color=#38bdf8>右端</color>。递增则<b>高估</b>。\n\n<size=92%><color=#a8b2d1>与左端镜像。</color></size>",
        13: "<b>中点法则：</b><color=#86efac>中点</color>取样，对称条带常更贴曲线。\n\n<size=92%><color=#a8b2d1>台阶落在每段中央。</color></size>",
        14: "<b>阻尼振动</b>—弹簧、电路。包络<color=#38bdf9>衰减</color>指数×正弦。\n\n<size=92%><color=#a8b2d1>导数仍决定峰附近安全柱。</color></size>",
        15: "悬链成<b>悬链线</b>，常用<color=#fde047>cosh</color>。不是抛体抛物线。\n\n<size=92%><color=#a8b2d1>拱与缆绳直觉。</color></size>",
        16: "<b>|sin(x)|</b> <color=#f0abfc>全波整流</color>波形，零点有尖角。\n\n<size=92%><color=#a8b2d1>从三角到电源波形。</color></size>",
        17: "<b>BC 反三角</b>。<color=#38bdf8>arctan</color>，1/(1+x²)。水平渐近线。\n\n<size=92%><color=#a8b2d1>积分与几何常客。</color></size>",
        18: "<b>逻辑斯蒂：</b>dP/dt = kP(1−P/L)。初段近指数，后向容量<b>L</b><color=#86efac>弯曲</color>。\n\n<size=92%><color=#a8b2d1>拐点处增长最快。</color></size>",
        19: "<b>极坐标</b><color=#fde047>(r,θ)</color>。<b>心形线</b> r ~ 1+cos θ。\n\n<size=92%><color=#a8b2d1>极面积 ½∫r² dθ。</color></size>",
        20: "<b>极坐标玫瑰</b> r ~ cos(nθ)。\n\n<size=92%><color=#a8b2d1>导数弹出标记r急变—花瓣边缘。</color></size>",
        21: "<b>sinh/cosh</b> 双曲恒等式、ODE、绳索。\n\n<size=92%><color=#a8b2d1>sinh是从0升起的奇伙伴。</color></size>",
        22: "<b>物理C：</b>Q = Q₀ e^{−t/τ}。RC/RL时间常数。\n\n<size=92%><color=#a8b2d1>曲线下沉，导数仍带“漏向零”的符号。</color></size>",
        23: "<b>转动</b><color=#7dd3fc>L = Iω</color>，τ = dL/dt。\n\n<size=92%><color=#a8b2d1>小振动同SHM，能量互换。</color></size>",
        24: "<b>抛体高度 y(t)</b> — 时间的<color=#fde047>抛物线</color>，v=0为顶点。\n\n<size=92%><color=#a8b2d1>y,v,a链条。</color></size>",
        25: "<b>cos 麦克劳林</b>偶次幂交替。\n\n<size=92%><color=#a8b2d1>更多项⇢0附近更准。</color></size>",
        26: "<b>ln x</b>与∫dx/x。\n\n<size=92%><color=#a8b2d1>正斜率渐细—收益递减。</color></size>",
        27: "<b>√x</b>在0⁺斜率爆炸（BC经典）。\n\n<size=92%><color=#a8b2d1>游玩采样光滑，解析提醒边界。</color></size>",
        28: "<b>tan x</b>渐近线之间的单枝。sec²x。\n\n<size=92%><color=#a8b2d1>BC参数/极坐标骨架。</color></size>",
        29: "<b>y′=ky ⇒ Ce^{kx}</b>。\n\n<size=92%><color=#a8b2d1>变化率正比于量。</color></size>",
        30: "<b>相位与SHM</b> sin(ωt+ϕ)。\n\n<size=92%><color=#a8b2d1>导数（差常数）如cos—谁先谁后。</color></size>",
        31: "<b>三次</b>—临界点、<color=#fca5a5>拐点</color>曲率翻转。\n\n<size=92%><color=#a8b2d1>典型丘谷图案。</color></size>",
        32: "<b>b^x</b>导数(ln b)b^x。\n\n<size=92%><color=#a8b2d1>把任意底连到e。</color></size>",
        33: "<b>圆</b>—上半圆 y=k+√(⋯)。\n\n<size=92%><color=#a8b2d1>隐函数与参数式AP最爱。</color></size>",
        34: "<b>升力C_L(α)</b>线性+<b>失速</b>折断。\n\n<size=92%><color=#a8b2d1>教学剪影非真机试验。</color></size>",
        35: "<b>阻力极曲线</b> C_D = C_{D0} + K C_L²。\n\n<size=92%><color=#a8b2d1>最佳升阻比直觉。</color></size>",
        36: "<b>等温大气</b>ρ ~ e^{−h/H}。\n\n<size=92%><color=#a8b2d1>动压等随ρ(h)。</color></size>",
        37: "<b>长周期/短周期</b>用阻尼振荡漫画化。\n\n<size=92%><color=#a8b2d1>真实飞控更复杂。</color></size>",
        38: "<b>牛顿型</b>~<color=#fca5a5>sin²α</color>迎风压—教学习题。\n\n<size=92%><color=#a8b2d1>非CFD。</color></size>",
        39: "<b>斯特劳哈尔</b>涡脱落频率 ~ St·U/D。\n\n<size=92%><color=#a8b2d1>振动与噪声线索。</color></size>",
        40: "<b>再入</b>热威胁曲线定性放松。\n\n<size=92%><color=#a8b2d1>非定量备忘录。</color></size>",
        41: "<b>互联网泡沫</b> — 示意指数走势（非真实标普数据）。\n\n<size=92%><color=#a8b2d1>爬升、急跌、缓慢修复的教学轮廓。</color></size>",
        42: "<b>2008危机</b> — 房贷与信用压力氛围，仅定性曲线。\n\n<size=92%><color=#a8b2d1>非下载行情；课堂斜率叙事。</color></size>",
        43: "<b>曼德博</b>c平面、光滑逃逸时间、固定Re切片。\n\n<size=92%><color=#a8b2d1>Julia边界；深 zoom 另需引擎。|Im(c)|切片。</color></size>",
    })

    # Arabic
    emit("ar", {
        0: "<color=#c4b5fd><b>المشتق</b></color> = ميل المماس — مدى صعود أو هبوط <b>f(x)</b>.\n\nالضيء الذهبي طريقك؛ الأزرق الجليدي هو f'(x) يصوّر <i>أين يثبت الأرض</i>. حيث |f'| كبير تبقى المنصات؛ وإلا يفتح الفراغ.\n\n<size=88%><color=#94a3b8><b>التفكير من المبادئ الأولى:</b> كشف التشبيه حتى الحقائق ثم البناء. <b>f</b> نموذج النتيجة؛ <b>f'</b> حساسية المدخلات.</color></size>",
        1: "مسافر يمشي حيث الميل لطيف. عندما يصبح المشتق سالباً، ينحسر الأرض إلى فجوة.",
        2: "المنحنى يصعد ويهبط كالتنفس. المشتق يحدد أين تهبط: موجب = خطوة آمنة، سالب = قفزة.",
        3: "جيب التمام يخبئ المعنى في إشارة مشتقه. الـ«pop» يعلن الخطر.",
        4: "القيمة المطلقة تطوي المنحنى إلى مسار واحد. عند القمة يقلب المشتق — ويتقلب الأرض.",
        5: "<color=#86efac>حدود تايلور</color> تلتف حول دالة ناعمة. <b>ماكلورين</b> = تايلور عند <b>0</b>.\n\nالمسار هنا مجموع جزئي من <b>e^u</b>.",
        6: "<color=#7dd3fc>قوى فردية لـ u</color> تبدل الإشارات — حمض نووي لـ <b>sin(u)</b>.\n\nبرج تايلور مقطوع نحو الموجة الجيبية.",
        7: "<color=#f5d0fe>متسلسلة هندسية</color> تكدس قوى <b>u</b>. داخل نصف القطر تذوب الذيل.\n\nمشتق المجموع المحدود يغيّر التضاريس.",
        8: "فكّر <b>z = x² − y₀²</b> — <color=#38bdf8>شريحة</color> <i>سرج</i>.\n\nمشتق x يقرأ متعدد المتغيرات بحركة بعد واحد.",
        9: "الآن <b>z = x² + y₀²</b> — <color=#fde047>قطع مكافئ إهليلجي</color>. تثبيت y₀ يعطي وعاءً في مستواك.\n\nالتدرج يصعد؛ الشريحة تبيّن انحدار الجري.",
        10: "<color=#fde047>التكامل المحدود</color> ل معدل غير سالب = <b>كمية متراكمة</b> — مساحة تحت المنحنى.\n\nالأعمدة الزرقاء <b>مجموع ريمان</b> f(x*)·Δx نحو ∫f.\n\n<size=92%><color=#a8b2d1>مسارك على المنحنى الناعم؛ التظليل يقارب التكامل.</color></size>",
        11: "<b>ريمان يساراً:</b> ارتفاع <b>f(xᵢ)</b> — <color=#f87171>اليسار</color>. إذا تزايدت f فالمجموع <b>يقلل</b> تقدير المساحة.\n\n<size=92%><color=#a8b2d1>درج منخفض تحت القطع المكافئ.</color></size>",
        12: "<b>ريمان يميناً:</b> <b>f(xᵢ₊₁)</b> — <color=#38bdf8>يمين</color> ⇒ <b>مزيد تقدير</b> عند التزايد.\n\n<size=92%><color=#a8b2d1>مرآة الحالة اليسرى.</color></size>",
        13: "<b>منتصف:</b> عينة في <color=#86efac>الوسط</color>. مستطيل متماثل؛ غالباً أدق.\n\n<size=92%><color=#a8b2d1>درجات في منتصف كل شريحة.</color></size>",
        14: "<b>اهتزاز مخمّد</b> — نوابض ودوائر. الغلاف <color=#38bdf9>ينكمش</color> أس × جيب.\n\n<size=92%><color=#a8b2d1>المشتق يختار أعمدة آمنة قرب القمم.</color></size>",
        15: "سلسلة معلّقة ⇒ <b>كتيناري</b> غالباً <color=#fde047>cosh</color>. ليست قذيفة.\n\n<size=92%><color=#a8b2d1>قوس وكوابل.</color></size>",
        16: "<b>|sin(x)|</b> جيب <color=#f0abfc>مقوّم كامل</b>.\n\n<size=92%><color=#a8b2d1>زوايا عند الصفر؛ المشتق يقفز.</color></size>",
        17: "<b>BC — عكس مثلثي.</b> <color=#38bdf8>arctan</color>، 1/(1+x²).\n\n<size=92%><color=#a8b2d1>خطوط مقاربة أفقية كحدود.</color></size>",
        18: "<b>لوجستي:</b> dP/dt = kP(1−P/L). شبه أسي ثم <color=#86efac>انحناء</color> نحو سعة <b>L</b>.\n\n<size=92%><color=#a8b2d1>نقطة انعطاف = أقصى نمو.</color></size>",
        19: "<b>قطبي</b> <color=#fde047>(r,θ)</color>. <b>قلب</b> r ~ 1+cos θ.\n\n<size=92%><color=#a8b2d1>مساحة ½∫ r² dθ.</color></size>",
        20: "<b>وردة</b> r ~ cos(nθ).\n\n<size=92%><color=#a8b2d1>قفزات المشتق حيث r يتغير بسرعة.</color></size>",
        21: "<b>sinh/cosh</b>، هوية الزائدية.\n\n<size=92%><color=#a8b2d1>sinh فردي من الصفر.</color></size>",
        22: "<b>فيزياء C:</b> Q = Q₀ e^{−t/τ}.\n\n<size=92%><color=#a8b2d1>المنحنى يهبط؛ المشتق يتسرب نحو صفر.</color></size>",
        23: "<b>دوران</b> <color=#7dd3fc>L = Iω</color>، τ = dL/dt.\n\n<size=92%><color=#a8b2d1>اهتزاز صغير مثل حركة توافقية.</color></size>",
        24: "<b>ارتفاع قذيفة y(t)</b> — <color=#fde047>قطع مكافئ</color> بالزمن. القمة عند v=0.\n\n<size=92%><color=#a8b2d1>سلسلة y,v,a.</color></size>",
        25: "<b>ماكلورين cos</b> بقوى زوجية.\n\n<size=92%><color=#a8b2d1>مزيد من الحدود ⇢ أدقى عند 0.</color></size>",
        26: "<b>ln x</b> و∫dx/x.\n\n<size=92%><color=#a8b2d1>ميل موجب يضعف ببعد.</color></size>",
        27: "<b>√x</b> ميل شديد عند 0⁺.\n\n<size=92%><color=#a8b2d1>اللعب أملس ؛ التحليل يحذر عند الحد.</color></size>",
        28: "<b>tan x</b> بين مقاربات. sec²x.\n\n<size=92%><color=#a8b2d1>عمود فقري لتمارين BC.</color></size>",
        29: "<b>y′=ky ⇒ Ce^{kx}</b>.\n\n<size=92%><color=#a8b2d1>معدل يتناسب مع الكمية.</color></size>",
        30: "<b>طور و SHM</b>.\n\n<size=92%><color=#a8b2d1>المشتق يقود بـ cos تقريباً.</color></size>",
        31: "<b>تكعيب</b> — نقاط حرجة، <color=#fca5a5>انعطاف</color>.\n\n<size=92%><color=#a8b2d1>نمط تلّ ووادٍ.</color></size>",
        32: "<b>b^x</b> بمشتق (ln b)b^x.\n\n<size=92%><color=#a8b2d1>جسر للأساس e.</color></size>",
        33: "<b>دائرة</b> — نصف علوي y=k+√(⋯).\n\n<size=92%><color=#a8b2d1>ضمني وباراميتر AP.</color></size>",
        34: "<b>رفع C_L(α)</b> خطي + <b>انفصال</b>.\n\n<size=92%><color=#a8b2d1>نموذج تعليمي.</color></size>",
        35: "<b>قطب سحب</b> C_D = C_{D0} + K C_L².\n\n<size=92%><color=#a8b2d1>حدس أفضل L/D.</color></size>",
        36: "<b>جو متساوي الحرارة</b> ρ ~ e^{−h/H}.\n\n<size=92%><color=#a8b2d1>الضغط الديناميكي يتبع ρ.</color></size>",
        37: "<b>مجنحة/قصيرة</b> كاهتزاز مخمّد مبسّط.\n\n<size=92%><color=#a8b2d1>التحكم الحقيقي أغنى.</color></size>",
        38: "<b>نيوتني</b> ~ sin²α تعليمي.\n\n<size=92%><color=#a8b2d1>ليس CFD.</color></size>",
        39: "<b>ستروهال</b> vortices.\n\n<size=92%><color=#a8b2d1>f ≈ St·U/D.</color></size>",
        40: "<b>دخول غلاف جوي</b> — <i>تخفيف نوعي</i> لمنحنى التسخين.\n\n<size=92%><color=#a8b2d1>ليس وثيقة كمية.</color></size>",
        41: "<b>فقاعة الدوت كوم</b> — مؤشر توضيحي (ليس S&amp;P الحقيقي).\n\n<size=92%><color=#a8b2d1>صعود، هبوط حاد، تعافٍ بطيء — تمثيل تعليمي.</color></size>",
        42: "<b>أزمة 2008</b> — رهن عقاري وضغط ائتمان، منحنى نوعي فقط.\n\n<size=92%><color=#a8b2d1>ليس بيانات فعلية.</color></size>",
        43: "<b>ماندلبرو</b> مستوى c، زمن هروب، شريح بـ Re ثابت.\n\n<size=92%><color=#a8b2d1>حد جوليا؛ تكبير عميق بمحرك آخر.</color></size>",
    })

    # Hindi
    emit("hi", {
        0: "<color=#c4b5fd><b>अवकलज</b></color> = स्पर्श रेखा की ढाल — <b>f(x)</b> कितनी तेज़ बदलता है।\n\nसुनहरी रोशनी आपका रास्ता; बर्फीला नीला f'(x) <i>ज़मीन कहाँ टिकती है</i> चुनता है। |f'| बड़ा ⇒ प्लैटफ़ॉर्म; छोटा ⇒ खाली।\n\n<size=88%><color=#94a3b8><b>फर्स्ट प्रिन्सिपल्स:</b> तुलना छीनकर तथ्य और फिर ऊपर तर्क। <b>f</b> परिणाम; <b>f'</b> इनपुट संवेदनशीलता।</color></size>",
        1: "यात्री मुलायम ढाल पर चलता है। अवकलज ऋणात्मक होते ये ज़मीन दरार बनती है।",
        2: "वक्र साँस की तरह उठता-गिरता है। अवकलज बताता है कहाँ उतरना है।",
        3: "कोज्या अपना अर्थ अवकलज के चिन्ह में छिपाता है। पॉप खतरे का संकेत।",
        4: "निरपेक्ष मान वक्र को एक पथ में मोड़ता है। शिखर पर अवकलज पलटता है — ज़मीन भी।",
        5: "<color=#86efac>टेलर बहुपद</color> चिकनी फलन को छूते हैं। <b>मैक्लॉरिन</b> <b>0</b> पर टेलर।\n\nयहाँ <b>e^u</b> का आंशिक योग।",
        6: "<color=#7dd3fc>विषम घात</color> चिन्ह बदलते — <b>sin(u)</b> की मैक्लॉरिन पहचान।\n\nकटा टॉवर साइन लहर की ओर।",
        7: "<color=#f5d0fe>ज्यामिति श्रृंखला</color> <b>u</b> की घातें। अर्धव्यास के भीतर पूँछ सिकुड़ती है।\n\nसीमित योग का अवकलज रूप बदलता है।",
        8: "<b>z = x² − y₀²</b> — <color=#38bdf8>खुरपरी</color> का काट।\n\nx-अवकलज बहुचर को 1D दौड़ में पढ़ता है।",
        9: "अब <b>z = x² + y₀²</b> — <color=#fde047>दीर्घवृत्तीय पैराबोलॉइड</color>। y₀ स्थिर कटोरा जैसा।\n\nढाल ऊपर चढ़ने की प्रवृत्ति दिखाता है।",
        10: "<color=#fde047>निश्चित समाकलन</color> दर को जोड़कर <b>कुल मात्रा</b> — वक्र के नीचे क्षेत्र।\n\nनीले स्तंभ <b>रीमान योग</b> ∫f की ओर।\n\n<size=92%><color=#a8b2d1>रास्ता चिकने ग्राफ पर; छाया समाकलन का अनुमान।</color></size>",
        11: "<b>बायाँ रीमान:</b> <b>f(xᵢ)</b> — <color=#f87171>बायाँ सिरा</color>। बद्ध f पर <b>कम</b> अनुमान।\n\n<size=92%><color=#a8b2d1>सावधान सीढ़ियाँ।</color></size>",
        12: "<b>दायाँ रीमान:</b> <b>f(xᵢ₊₁)</b> — <color=#38bdf8>दायाँ</color>। बद्ध f पर <b>अधिक</b> अनुमान।\n\n<size=92%><color=#a8b2d1>बाएँ का दर्पण।</color></size>",
        13: "<b>मध्यबिंदु:</b> <color=#86efac>केंद्र</color> पर नमूना। अक्सर सटीक।\n\n<size=92%><color=#a8b2d1>हर फीते के बीच सीढ़ी।</color></size>",
        14: "<b>मंद दोलन</b> — स्प्रिंग, परिपथ। लिफाफा <color=#38bdf9>घटता</color> exp×sin।\n\n<size=92%><color=#a8b2d1>अवकलज शिखर के पास सुरक्षित स्तंभ चुनता है।</color></size>",
        15: "लटकती ज़ंजीर ⇒ <b>कैटनरी</b>, अक्सर <color=#fde047>cosh</color>। प्रक्षेप्य परबोला नहीं।\n\n<size=92%><color=#a8b2d1>मेहराब-तार।</color></size>",
        16: "<b>|sin(x)|</b> <color=#f0abfc>पूल-तरंग निर्देशित</color>। शून्य पर कोण।\n\n<size=92%><color=#a8b2d1>त्रिकोणमिति से पावर इलेक्ट्रॉनिक्स।</color></size>",
        17: "<b>BC व्युत्क्रम त्रिक</b>। <color=#38bdf8>arctan</color>, 1/(1+x²)।\n\n<size=92%><color=#a8b2d1>क्षैतिज असिम्पटोट।</color></size>",
        18: "<b>लॉजिस्टिक:</b> dP/dt = kP(1−P/L)। शुरू में लगभग घात, फिर <color=#86efac>L</color> की ओर मोड़।\n\n<size=92%><color=#a8b2d1>बिंदु प्रगाढ़ता = अधिकतम वृद्धि।</color></size>",
        19: "<b>ध्रुवीय</b> <color=#fde047>(r,θ)</color>। <b>कार्डियॉयड</b> r ~ 1+cos θ.\n\n<size=92%><color=#a8b2d1>क्षेत्रफल ½∫r² dθ.</color></size>",
        20: "<b>गुलाब</b> r ~ cos(nθ).\n\n<size=92%><color=#a8b2d1>अवकलज पॉप जहाँ r तेज़ बदले।</color></size>",
        21: "<b>sinh/cosh</b> अतिपरवलयिक पहचान।\n\n<size=92%><color=#a8b2d1>sinh विषम साथी।</color></size>",
        22: "<b>भौतिकी C:</b> Q = Q₀ e^{−t/τ}.\n\n<size=92%><color=#a8b2d1>वक्र नीचे; अवकलज शून्य की ओर।</color></size>",
        23: "<b>घूर्णन</b> <color=#7dd3fc>L = Iω</color>, τ = dL/dt.\n\n<size=92%><color=#a8b2d1>छोटा दोलन SHM जैसा।</color></size>",
        24: "<b>प्रक्षेप्य ऊँचाई y(t)</b> — समय में <color=#fde047>परबोला</color>, शिखर v=0.\n\n<size=92%><color=#a8b2d1>y,v,a कड़ियाँ।</color></size>",
        25: "<b>मैक्लॉरिन cos</b> सम घातें।\n\n<size=92%><color=#a8b2d1>अधिक पद ⇒ 0 के पास बेहतर।</color></size>",
        26: "<b>ln x</b> व ∫dx/x.\n\n<size=92%><color=#a8b2d1>ढाल ह्रासमान।</color></size>",
        27: "<b>√x</b> 0⁺ पर अनंत ढाल।\n\n<size=92%><color=#a8b2d1>खेल चिकना; विश्लेषण चेतावनी।</color></size>",
        28: "<b>tan x</b> असिम्पटोट के बीच शाखा।\n\n<size=92%><color=#a8b2d1>BC त्रिक कंकाल।</color></size>",
        29: "<b>y′=ky ⇒ Ce^{kx}</b>.\n\n<size=92%><color=#a8b2d1>दर मात्रा के अनुपाती।</color></size>",
        30: "<b>कला व SHM</b>.\n\n<size=92%><color=#a8b2d1>अवकलज lag/cos कहानी।</color></size>",
        31: "<b>घन</b> — गुणक, <color=#fca5a5>प्रगाढ़ता</color>.\n\n<size=92%><color=#a8b2d1>पहाड़-घाटी नमूना।</color></size>",
        32: "<b>b^x</b> अवकलज (ln b)b^x.\n\n<size=92%><color=#a8b2d1>आधार e पुल।</color></size>",
        33: "<b>वृत्त</b> — ऊपरी अर्धवृत्त y=k+√(⋯).\n\n<size=92%><color=#a8b2d1>अप्रत्यक्ष व पैरामीट्रिक AP।</color></size>",
        34: "<b>लिफ़्ट C_L(α)</b> रेखीय + <b>स्टॉल</b>.\n\n<size=92%><color=#a8b2d1>शिक्षण सिल्हूट</color></size>",
        35: "<b>ड्रैग पोलर</b> C_D = C_{D0} + K C_L².\n\n<size=92%><color=#a8b2d1>उत्तम L/D अंतर्ज्ञान।</color></size>",
        36: "<b>समतापमान वायुमंडल</b> ρ ~ e^{−h/H}.\n\n<size=92%><color=#a8b2d1>गतिक दाब ρ पर।</color></size>",
        37: "<b>फ्यूगॉइड/लघु</b> मंद कार्टून।\n\n<size=92%><color=#a8b2d1>वास्तविक नियंत्रण समृद्ध।</color></size>",
        38: "<b>न्यूटनी ~ sin²α</b> शिक्षा मॉडल.\n\n<size=92%><color=#a8b2d1>CFD नहीं।</color></size>",
        39: "<b>स्ट्रौहल</b> शेडिंग.\n\n<size=92%><color=#a8b2d1>f ≈ St·U/D.</color></size>",
        40: "<b>पुनः प्रवेश</b> गर्मी वक्र ढील।\n\n<size=92%><color=#a8b2d1>मात्रात्मक मेमो नहीं।</color></size>",
        41: "<b>डॉट-कॉम बुलबुला</b> — नमूना सूचकांक (वास्तविक S&amp;P नहीं)।\n\n<size=92%><color=#a8b2d1>उछाल, गिरावट, धीमी वसूली — शिक्षण रूपक।</color></size>",
        42: "<b>2008 संकट</b> — गिरवी/क्रेडिट तनाव माहौल, केवल गुणात्मक।\n\n<size=92%><color=#a8b2d1>वास्तविक डेटा पुनर्निर्माण नहीं।</color></size>",
        43: "<b>मैंडेलब्रॉट</b> c-तल, भागने का समय, स्थिर Re काट।\n\n<size=92%><color=#a8b2d1>जुलिया सीमा; गहरा ज़ूम अलग इंजन।</color></size>",
    })

    # Urdu
    emit("ur", {
        0: "<color=#c4b5fd><b>مشتق</b></color> = مماس کی ڈھلوان — <b>f(x)</b> کتنی تیزی سے بدلتا ہے۔\n\nسنہرا راستہ؛ برف نیلا f'(x) <i>فرش کہاں تھامتا ہے</i>۔ |f'| بڑا ⇒ پلیٹ فارم؛ ورنہ خلا۔\n\n<size=88%><color=#94a3b8><b>اول اصول:</b> مماثلت ہٹا کر حقیقت پر دوبارہ تعمیر۔ <b>f</b> نتیجہ؛ <b>f'</b> ان پٹ حساسیت۔</color></size>",
        1: "مسافر نرم ڈھلوان پر چلتا ہے۔ مشتق منفی ہوتے فرش درز بن جاتا ہے۔",
        2: "منحنی سانس کی طرح۔ مشتق بتاتا ہے کہاں اترنا ہے۔",
        3: "کوسائن معنی مشتق کے اشارے میں چھپاتا ہے۔ پوپ خطرہ۔",
        4: "مطلق قیمت منحنی ایک راستے میں موڑتی ہے۔ چوٹی پر مشتق پلٹتا ہے — فرش بھی۔",
        5: "<color=#86efac>ٹیلر کثیر رکنی</color> ہموار فنکشن کے قریب۔ <b>میکلارن</b> <b>0</b> پر ٹیلر۔\n\nیہاں <b>e^u</b> جزوی مجموعہ۔",
        6: "<color=#7dd3fc>طاق طاقتیں</color> نشان بدلتی ہیں — <b>sin(u)</b> کی میکلارن شناخت۔\n\nکاٹا ٹاور سائن لہر کی طرف۔",
        7: "<color=#f5d0fe>جومیٹرک سیریز</color> <b>u</b> کی طاقٹیں۔ ریڈیئس میں دم گھٹتا ہے۔\n\nمحدود مجموعے کا مشقق منظر بدلتا ہے۔",
        8: "<b>z = x² − y₀²</b> — زن کی <color=#38bdf8>سلائس</color> (saddle)۔\n\nx پر مشتق کثیر متغیر کو ایک جہتی حرکت میں پڑھتا ہے۔",
        9: "اب <b>z = x² + y₀²</b> — <color=#fde047>بیضوی تھری ڈی قطع مکافئ</color>۔ مستقل y₀ پر کٹورے جیسا قطع۔\n\ngradient اوپر چڑھتا ہے؛ سلائس ڈھلوان دکھاتا ہے۔",
        10: "<color=#fde047>محدود انٹیگرل</color> شرح جمع = <b>کل</b> — منحنی کے نیچے رقبہ۔\n\nنیلے ستون <b>ریمان</b> ∫f کی طرف۔\n\n<size=92%><color=#a8b2d1>راستہ ہموار گراف؛ شیڈنگ قریبی انٹیگرل۔</color></size>",
        11: "<b>بائیں ریمان:</b> <b>f(xᵢ)</b> — <color=#f87171>بایاں کنارہ</color>۔ بڑھتے f پر <b>کم</b> تخمینہ۔\n\n<size=92%><color=#a8b2d1>احتیاطی سیڑھیاں۔</color></size>",
        12: "<b>دائاں ریمان:</b> <b>f(xᵢ₊₁)</b> — <color=#38bdf8>دایاں</color>۔ بڑھتے f پر <b>زیادہ</b>۔\n\n<size=92%><color=#a8b2d1>بائیں کا آئینہ۔</color></size>",
        13: "<b>وسط:</b> <color=#86efac>مرکز</color> پر نمونہ۔ اکثر قریب۔\n\n<size=92%><color=#a8b2d1>ہر پٹی کے بیچ سیڑھی۔</color></size>",
        14: "<b>ڈیمپ شدہ ارتعاش</b> — Spring، سرکٹ۔ لفافہ <color=#38bdf9>سکڑتا</color> ہے۔\n\n<size=92%><color=#a8b2d1>مشتق چوٹی کے قریب محفوظ ستون۔</color></size>",
        15: "لٹکی زنجیر ⇒ <b>کیٹنری</b>، اکثر <color=#fde047>cosh</color>۔\n\n<size=92%><color=#a8b2d1>مہراب/تار۔</color></size>",
        16: "<b>|sin(x)|</b> <color=#f0abfc>مکمل لہر دونوں طرف سے دھری ہوئی</color> (rectified)۔\n\n<size=92%><color=#a8b2d1>صفر پر تیز گوشے۔</color></size>",
        17: "<b>BC معکوس Trig</b>۔ <color=#38bdf8>arctan</color>.\n\n<size=92%><color=#a8b2d1>افقی Asymptotes۔</color></size>",
        18: "<b>لاجسٹک:</b> dP/dt = kP(1−P/L)۔ شروع میں تقریباً نمائی نمو، پھر <color=#86efac>L</color> کی طرف موڑ۔\n\n<size=92%><color=#a8b2d1>انفلیکشن پر زیادہ تر نمو۔</color></size>",
        19: "<b>قطبی</b> <color=#fde047>(r,θ)</color>۔ <b>کارڈیائڈ</b>.\n\n<size=92%><color=#a8b2d1>رقبہ ½∫r² dθ۔</color></size>",
        20: "<b>گلاب</b> r ~ cos(nθ).\n\n<size=92%><color=#a8b2d1>مشتق پاپ جہاں r تیز بدلے۔</color></size>",
        21: "<b>sinh/cosh</b>.\n\n<size=92%><color=#a8b2d1>sinh مزاحم ساتھی۔</color></size>",
        22: "<b>جسمانیات C:</b> Q = Q₀ e^{−t/τ}.\n\n<size=92%><color=#a8b2d1>گراف نیچے؛ مشتق صفر کی طرف۔</color></size>",
        23: "<b>گھومنا</b> <color=#7dd3fc>L = Iω</color>.\n\n<size=92%><color=#a8b2d1>چھوٹا SHM جیسا۔</color></size>",
        24: "<b>موزون y(t)</b> — وقت میں <color=#fde047>مکافئ</color>؛ چوٹی پر v=0.\n\n<size=92%><color=#a8b2d1>سلسلہ y، v، a۔</color></size>",
        25: "<b>میکلارن cos</b>.\n\n<size=92%><color=#a8b2d1>زیادہ اصطلاحات 0 قریب بہتر۔</color></size>",
        26: "<b>ln x</b>.\n\n<size=92%><color=#a8b2d1>مثبت ڈھلوان دور ہو کر کم۔</color></size>",
        27: "<b>√x</b> 0⁺ پر ڈھلوان۔\n\n<size=92%><color=#a8b2d1>کھیل ہموار؛ انتباہ سرحد۔</color></size>",
        28: "<b>tan x</b>۔\n\n<size=92%><color=#a8b2d1>BC میں مثلثیات کا ڈھانچہ۔</color></size>",
        29: "<b>y′=ky</b>.\n\n<size=92%><color=#a8b2d1>شرح متناسب۔</color></size>",
        30: "<b>مرحلہ / SHM</b>.\n\n<size=92%><color=#a8b2d1>مشتق تقریباً cos۔</color></size>",
        31: "<b>مکعب</b> — <color=#fca5a5>انفلیکشن</color>.\n\n<size=92%><color=#a8b2d1> پہاڑ وادی نمونہ۔</color></size>",
        32: "<b>b^x</b> کا مشتق (ln b)b^x.\n\n<size=92%><color=#a8b2d1>کسی بھی اڈے کو e سے جوڑتا ہے۔</color></size>",
        33: "<b>دائرہ</b> — اوپری نیم دائرہ۔\n\n<size=92%><color=#a8b2d1>ضمنی اور پیرامیٹرک AP کے مسائل۔</color></size>",
        34: "<b>لفٹ C_L</b> لکیری + <b>اسٹال</b>.\n\n<size=92%><color=#a8b2d1>تدریسی۔</color></size>",
        35: "<b>ڈریگ polar</b>.\n\n<size=92%><color=#a8b2d1>بہترین L/D۔</color></size>",
        36: "<b>موسم</b> ρ ~ e^{−h/H}.\n\n<size=92%><color=#a8b2d1>دائمی دباؤ ρ۔</color></size>",
        37: "<b>فگوئڈ</b> ڈیمپ کارٹون۔\n\n<size=92%><color=#a8b2d1>اصلی کنٹرول زیادہ۔</color></size>",
        38: "<b>Newtonian</b> تعلیم۔\n\n<size=92%><color=#a8b2d1>CFDنہیں۔</color></size>",
        39: "<b>Strouhal</b>.\n\n<size=92%><color=#a8b2d1>f ≈ St·U/D۔</color></size>",
        40: "<b>دوبارہ دخول</b> نِرم گرم منحنی۔\n\n<size=92%><color=#a8b2d1>مقدار نوٹ نہیں۔</color></size>",
        41: "<b>ڈاٹ کام ببل</b> — اسٹائل شدہ انڈیکس (اصلی S&amp;P نہیں)۔\n\n<size=92%><color=#a8b2d1>چڑھاو، گراو، آہستہ بحالی — تعلیمی شکل۔</color></size>",
        42: "<b>2008 بحران</b> — رہن/کریڈٹ دباؤ، صرف کوالٹیٹیو۔\n\n<size=92%><color=#a8b2d1>حقیقی ڈیٹا نقل نہیں۔</color></size>",
        43: "<b>مینڈلبروٹ</b>۔\n\n<size=92%><color=#a8b2d1>julia سرحد۔</color></size>",
    })
